server:
  port: 8081
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/  # 前缀
      suffix: .jsp  # 后缀
  #redis缓存配置
  redis:
    host: 127.0.0.1  #配置redis的主机地址，需要修改成自己的
    database: 5
    port: 6379
    #password: root
    jedis:
      pool:
        max-active: 50 # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool 的状态为exhausted(耗尽)
        max-idle: 20 # 连接池中的最大空闲连接，默认值也是8。
        min-idle: 5  # 连接池中的最小空闲连接，默认值也是0。
        # max-wait: 5 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接 抛出JedisConnectionException
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.redpacket.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true